### ISSUE TITLE
Intellij-IDEA-Ultimate freezes on startup when it is trying to connect to an available database.

### ISSUE THREAD

**Issue by IslamYusuf** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#126]
The app freezes on startup when a database has been setup using the database tab of the app. If a remove all database connections Intellij doesn't freeze on startup. It shows the following errors when run from the terminal:

2023-01-30 07:44:40,111 [   1944]   WARN - #c.i.u.ExperimentalUIImpl - Can't find GridIconMappings.json
2023-01-30 07:44:45,902 [   7735]   WARN - #c.i.e.RunManager - Must be not called before project components initialized
2023-01-30 07:44:47,127 [   8960]   WARN - #c.i.u.x.Binding - no accessors for com.intellij.openapi.project.Project
2023-01-30 07:44:47,176 [   9009] SEVERE - #c.i.c.e.InspectionProfileImpl - Can't read settings for com.haulmont.jpb.CompositeIdClassSerializable
com.intellij.openapi.util.InvalidDataException: com.intellij.util.xmlb.XmlSerializationException: java.util.NoSuchElementException: List is empty.
	at com.intellij.codeInspection.InspectionProfileEntry.readSettings(InspectionProfileEntry.java:367)
	at com.intellij.codeInspection.ex.ScopeToolState.tryReadSettings(ScopeToolState.java:156)
	at com.intellij.codeInspection.ex.ToolsImpl.readExternal(ToolsImpl.java:230)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.addTool(InspectionProfileImpl.java:580)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:485)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:113)
	at com.intellij.profile.codeInspection.ProjectInspectionProfileManager.initializeComponent(ProjectInspectionProfileManager.kt:92)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:131)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:46)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:581)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:19)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:181)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService$suspendImpl(ComponentManagerImpl.kt:1140)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invokeSuspend(ComponentManagerImpl.kt:1116)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.intellij.util.xmlb.XmlSerializationException: java.util.NoSuchElementException: List is empty.
	at com.intellij.configurationStore.JdomSerializerImpl.deserializeInto(xmlSerializer.kt:115)
	at com.intellij.configurationStore.XmlSerializer.deserializeInto(xmlSerializer.kt:31)
	at com.intellij.codeInspection.InspectionProfileEntry.readSettings(InspectionProfileEntry.java:364)
	... 32 more
Caused by: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:197)
	at com.intellij.serialization.BaseBeanBindingKt.createUsingKotlin(BaseBeanBinding.kt:49)
	at com.intellij.serialization.BaseBeanBindingKt.access$createUsingKotlin(BaseBeanBinding.kt:1)
	at com.intellij.serialization.BaseBeanBinding.newInstance(BaseBeanBinding.kt:34)
	at com.intellij.serialization.xml.KotlinAwareBeanBinding.newInstance(KotlinAwareBeanBinding.kt:76)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:142)
	at com.intellij.util.xmlb.NotNullDeserializeBinding.deserializeUnsafe(NotNullDeserializeBinding.java:20)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:29)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:108)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:54)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:246)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:200)
	at com.intellij.configurationStore.JdomSerializerImpl.deserializeInto(xmlSerializer.kt:109)
	... 34 more
2023-01-30 07:44:47,195 [   9028] SEVERE - #c.i.c.e.InspectionProfileImpl - IntelliJ IDEA 2022.3.2  Build #IU-223.8617.56
2023-01-30 07:44:47,195 [   9028] SEVERE - #c.i.c.e.InspectionProfileImpl - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-01-30 07:44:47,196 [   9029] SEVERE - #c.i.c.e.InspectionProfileImpl - OS: Linux
Info  | RdCoroutineScope          | 55:DefaultDispatcher-worker-38 | RdCoroutineHost overridden 
2023-01-30 07:44:49,111 [  10944]   WARN - #o.j.i.maven - Using extension org.jetbrains.idea.maven.maven3.Maven3Support@2c76807b to start MavenServer
2023-01-30 07:44:54,654 [  16487]   WARN - #c.i.o.a.i.ActionUpdater - 431 ms to grab EDT for ProjectToolbarWidgetAction#update@MainToolbar (com.intellij.openapi.wm.impl.headertoolbar.ProjectToolbarWidgetAction)
2023-01-30 07:44:55,231 [  17064]   WARN - #c.i.o.a.i.ActionUpdater - 470 ms to grab EDT for ProjectToolbarWidgetAction#update@MainToolbar (com.intellij.openapi.wm.impl.headertoolbar.ProjectToolbarWidgetAction)
2023-01-30 07:44:56,143 [  17976]   WARN - #c.i.o.w.i.c.h.t.MainMenuButton - rootPane is not set, MainMenu button listeners are not installed
2023-01-30 07:44:56,744 [  18577]   WARN - #c.i.o.a.i.ActionUpdater - 713 ms to grab EDT for FontEditorPreview$ToggleBoldFontAction#update@ContextToolbar (com.intellij.application.options.colors.FontEditorPreview$ToggleBoldFontAction)
2023-01-30 07:44:57,049 [  18882]   WARN - #c.i.o.a.i.ActionUpdater - 511 ms to grab EDT for LiveEditActionProvider$createAction$1#update@EditorInspectionsToolbar (com.android.tools.idea.editors.liveedit.ui.LiveEditActionProvider$createAction$1)
Changing log factory from com.intellij.idea.LoggerFactory to com.haulmont.jpb.logger.JpabLoggerFactory
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.logFactoryChanged(Logger.java:79)
	at com.intellij.openapi.diagnostic.Logger.setFactory(Logger.java:70)
	at com.haulmont.jpb.action.persistenceunit.PersistenceUnitStartupActivity.runActivity(PersistenceUnitStartupActivity.kt:44)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$3.invoke$lambda$0(StartupManagerImpl.kt:295)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:388)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:380)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

2023-01-30 07:47:21,200 [ 163033]   WARN - #c.i.u.x.Binding - no accessors for com.haulmont.jpb.model.dbtype.DbType
2023-01-30 07:47:21,513 [ 163346]   WARN - #c.i.u.x.Binding - no accessors for com.intellij.lang.annotation.HighlightSeverity
2023-01-30 07:47:26,455 [ 168288] SEVERE - #c.i.v.l.d.i.IndexDiagnosticRunner - Index is corrupted
2023-01-30 07:44:40,111 [   1944]   WARN - #c.i.u.ExperimentalUIImpl - Can't find GridIconMappings.json
2023-01-30 07:44:45,902 [   7735]   WARN - #c.i.e.RunManager - Must be not called before project components initialized
2023-01-30 07:44:47,127 [   8960]   WARN - #c.i.u.x.Binding - no accessors for com.intellij.openapi.project.Project
2023-01-30 07:44:47,176 [   9009] SEVERE - #c.i.c.e.InspectionProfileImpl - Can't read settings for com.haulmont.jpb.CompositeIdClassSerializable
com.intellij.openapi.util.InvalidDataException: com.intellij.util.xmlb.XmlSerializationException: java.util.NoSuchElementException: List is empty.
	at com.intellij.codeInspection.InspectionProfileEntry.readSettings(InspectionProfileEntry.java:367)
	at com.intellij.codeInspection.ex.ScopeToolState.tryReadSettings(ScopeToolState.java:156)
	at com.intellij.codeInspection.ex.ToolsImpl.readExternal(ToolsImpl.java:230)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.addTool(InspectionProfileImpl.java:580)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:485)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:113)
	at com.intellij.profile.codeInspection.ProjectInspectionProfileManager.initializeComponent(ProjectInspectionProfileManager.kt:92)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:131)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:46)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:581)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:19)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:181)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService$suspendImpl(ComponentManagerImpl.kt:1140)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invokeSuspend(ComponentManagerImpl.kt:1116)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.intellij.util.xmlb.XmlSerializationException: java.util.NoSuchElementException: List is empty.
	at com.intellij.configurationStore.JdomSerializerImpl.deserializeInto(xmlSerializer.kt:115)
	at com.intellij.configurationStore.XmlSerializer.deserializeInto(xmlSerializer.kt:31)
	at com.intellij.codeInspection.InspectionProfileEntry.readSettings(InspectionProfileEntry.java:364)
	... 32 more
Caused by: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:197)
	at com.intellij.serialization.BaseBeanBindingKt.createUsingKotlin(BaseBeanBinding.kt:49)
	at com.intellij.serialization.BaseBeanBindingKt.access$createUsingKotlin(BaseBeanBinding.kt:1)
	at com.intellij.serialization.BaseBeanBinding.newInstance(BaseBeanBinding.kt:34)
	at com.intellij.serialization.xml.KotlinAwareBeanBinding.newInstance(KotlinAwareBeanBinding.kt:76)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:142)
	at com.intellij.util.xmlb.NotNullDeserializeBinding.deserializeUnsafe(NotNullDeserializeBinding.java:20)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:29)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:108)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:54)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:246)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:200)
	at com.intellij.configurationStore.JdomSerializerImpl.deserializeInto(xmlSerializer.kt:109)
	... 34 more
2023-01-30 07:44:47,195 [   9028] SEVERE - #c.i.c.e.InspectionProfileImpl - IntelliJ IDEA 2022.3.2  Build #IU-223.8617.56
2023-01-30 07:44:47,195 [   9028] SEVERE - #c.i.c.e.InspectionProfileImpl - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-01-30 07:44:47,196 [   9029] SEVERE - #c.i.c.e.InspectionProfileImpl - OS: Linux
Info  | RdCoroutineScope          | 55:DefaultDispatcher-worker-38 | RdCoroutineHost overridden 
2023-01-30 07:44:49,111 [  10944]   WARN - #o.j.i.maven - Using extension org.jetbrains.idea.maven.maven3.Maven3Support@2c76807b to start MavenServer
2023-01-30 07:44:54,654 [  16487]   WARN - #c.i.o.a.i.ActionUpdater - 431 ms to grab EDT for ProjectToolbarWidgetAction#update@MainToolbar (com.intellij.openapi.wm.impl.headertoolbar.ProjectToolbarWidgetAction)
2023-01-30 07:44:55,231 [  17064]   WARN - #c.i.o.a.i.ActionUpdater - 470 ms to grab EDT for ProjectToolbarWidgetAction#update@MainToolbar (com.intellij.openapi.wm.impl.headertoolbar.ProjectToolbarWidgetAction)
2023-01-30 07:44:56,143 [  17976]   WARN - #c.i.o.w.i.c.h.t.MainMenuButton - rootPane is not set, MainMenu button listeners are not installed
2023-01-30 07:44:56,744 [  18577]   WARN - #c.i.o.a.i.ActionUpdater - 713 ms to grab EDT for FontEditorPreview$ToggleBoldFontAction#update@ContextToolbar (com.intellij.application.options.colors.FontEditorPreview$ToggleBoldFontAction)
2023-01-30 07:44:57,049 [  18882]   WARN - #c.i.o.a.i.ActionUpdater - 511 ms to grab EDT for LiveEditActionProvider$createAction$1#update@EditorInspectionsToolbar (com.android.tools.idea.editors.liveedit.ui.LiveEditActionProvider$createAction$1)
Changing log factory from com.intellij.idea.LoggerFactory to com.haulmont.jpb.logger.JpabLoggerFactory
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.logFactoryChanged(Logger.java:79)
	at com.intellij.openapi.diagnostic.Logger.setFactory(Logger.java:70)
	at com.haulmont.jpb.action.persistenceunit.PersistenceUnitStartupActivity.runActivity(PersistenceUnitStartupActivity.kt:44)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$3.invoke$lambda$0(StartupManagerImpl.kt:295)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:388)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:380)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

2023-01-30 07:47:21,200 [ 163033]   WARN - #c.i.u.x.Binding - no accessors for com.haulmont.jpb.model.dbtype.DbType
2023-01-30 07:47:21,513 [ 163346]   WARN - #c.i.u.x.Binding - no accessors for com.intellij.lang.annotation.HighlightSeverity
2023-01-30 07:47:26,455 [ 168288] SEVERE - #c.i.v.l.d.i.IndexDiagnosticRunner - Index is corrupted

Diff for commit 729ae757...
Filtering by files:[############] does not return 729ae757

java.lang.RuntimeException: Index is corrupted
	at com.intellij.vcs.log.data.index.IndexDiagnosticRunner.runDiagnostic(IndexDiagnosticRunner.kt:54)
	at com.intellij.vcs.log.data.index.IndexDiagnosticRunner.onDataPackChange(IndexDiagnosticRunner.kt:66)
	at com.intellij.vcs.log.data.VcsLogData.fireDataPackChangeEvent(VcsLogData.java:246)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl.lambda$new$0(VcsLogRefresherImpl.java:81)
	at com.intellij.vcs.log.data.SingleTaskController.taskCompleted(SingleTaskController.java:156)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl$MyRefreshTask.run(VcsLogRefresherImpl.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-30 07:47:26,460 [ 168293] SEVERE - #c.i.v.l.d.i.IndexDiagnosticRunner - IntelliJ IDEA 2022.3.2  Build #IU-223.8617.56
2023-01-30 07:47:26,460 [ 168293] SEVERE - #c.i.v.l.d.i.IndexDiagnosticRunner - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-01-30 07:47:26,460 [ 168293] SEVERE - #c.i.v.l.d.i.IndexDiagnosticRunner - OS: Linux
^C
2023-01-30 07:53:07,738 [ 509571]   WARN - #c.i.o.v.i.l.NativeFileWatcherImpl - Watcher terminated with exit code 130

**Comment by x80486** [comment]
Would you be able to explain how can I duplicate this issue (database, driver, etc.)? I do have several databases setup as well within `IDEA`, but I don't get any errors initially.

Also, what exactly do you mean by "the app freezes on startup when a database has been setup"? Were you describing starting `IDEA` on its own, or trying to open up any of the associated projects. Do you have any other database setup?

Reason I'm asking is because it doesn't look like, initially, as a problem with `Flatpak`, so I'm trying to isolate some things. It would be great if you are able to do the same with the official build, although sometimes it's a little bit difficult to have the same config to replicate something.
